// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjzGKGfhZXQ5ABbLScEOif9khvV9wTV6Q',
    appId: '1:472789077581:web:857950c267e3d7db5d5604',
    messagingSenderId: '472789077581',
    projectId: 'arewecookin',
    authDomain: 'arewecookin.firebaseapp.com',
    databaseURL: 'https://arewecookin-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'arewecookin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0fMFrBIRuICTukwV41Lw_JYTFS-b0nu0',
    appId: '1:472789077581:android:7e54c577d178feba5d5604',
    messagingSenderId: '472789077581',
    projectId: 'arewecookin',
    databaseURL: 'https://arewecookin-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'arewecookin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvLnTjl7FvAjEs6-In24MYpsqdSING2kA',
    appId: '1:472789077581:ios:126fbdb4be574c8a5d5604',
    messagingSenderId: '472789077581',
    projectId: 'arewecookin',
    databaseURL: 'https://arewecookin-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'arewecookin.firebasestorage.app',
    iosBundleId: 'com.example.arewecookin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvLnTjl7FvAjEs6-In24MYpsqdSING2kA',
    appId: '1:472789077581:ios:126fbdb4be574c8a5d5604',
    messagingSenderId: '472789077581',
    projectId: 'arewecookin',
    databaseURL: 'https://arewecookin-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'arewecookin.firebasestorage.app',
    iosBundleId: 'com.example.arewecookin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjzGKGfhZXQ5ABbLScEOif9khvV9wTV6Q',
    appId: '1:472789077581:web:119916f09c9e62155d5604',
    messagingSenderId: '472789077581',
    projectId: 'arewecookin',
    authDomain: 'arewecookin.firebaseapp.com',
    databaseURL: 'https://arewecookin-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'arewecookin.firebasestorage.app',
  );
}
